<?php
$specialMarkup = [
    "doctype"   => "meta.tag.metadata.doctype",
    "cdata"     => "meta.tag.metadata.cdata",
    "comment"   => "punctuation.definition.comment",
    "text"      => "text.html.basic",
];
$genericMarkup = [
    "punctuactionTag"       => "punctuation.definition.tag",
    "punctuactionOpenTag"   => "punctuation.definition.tag.begin.html",
    "punctuactionCloseTag"  => "punctuation.definition.tag.end.html",

    "entitiTagName"         => "entity.name.tag.html",

    "attributeName"         => "entity.other.attribute-name.html",
    "attributeEqual"        => "punctuation.separator.key-value.html",
    "attributeOpenQuote"    => "punctuation.definition.string.begin.html",
    "attributeCloseQuote"   => "punctuation.definition.string.end.html",
    "attributeValue"        => "string.quoted.double.html",
];
$emptyTags = [
    "area", "base", "basefont", "br", "col", "embed",
    "frame", "hr", "img", "input", "link", "meta",
    "param", "source", "track", "wbr"
];
$htmlTags = [
    "address"           => "meta.tag.structure.address",
    "article"           => "meta.tag.structure.article",
    "aside"             => "meta.tag.structure.aside",
    "blockquote"        => "meta.tag.structure.blockquote",
    "body"              => "meta.tag.structure.body",
    "button"            => "meta.tag.structure.button",
    "caption"           => "meta.tag.structure.caption",
    "center"            => "meta.tag.structure.center",
    "col"               => "meta.tag.structure.col",
    "colgroup"          => "meta.tag.structure.colgroup",
    "datalist"          => "meta.tag.structure.datalist",
    "dd"                => "meta.tag.structure.dd",
    "details"           => "meta.tag.structure.details",
    "dialog"            => "meta.tag.structure.dialog",
    "div"               => "meta.tag.structure.div",
    "dl"                => "meta.tag.structure.dl",
    "dt"                => "meta.tag.structure.dt",
    "fieldset"          => "meta.tag.structure.fieldset",
    "figcaption"        => "meta.tag.structure.figcaption",
    "figure"            => "meta.tag.structure.figure",
    "footer"            => "meta.tag.structure.footer",
    "form"              => "meta.tag.structure.form",
    "frameset"          => "meta.tag.structure.frameset",
    "h1"                => "meta.tag.structure.h1",
    "h2"                => "meta.tag.structure.h2",
    "h3"                => "meta.tag.structure.h3",
    "h4"                => "meta.tag.structure.h4",
    "h5"                => "meta.tag.structure.h5",
    "h6"                => "meta.tag.structure.h6",
    "head"              => "meta.tag.structure.head",
    "header"            => "meta.tag.structure.header",
    "hr"                => "meta.tag.structure.hr",
    "html"              => "meta.tag.structure.html",
    "input"             => "meta.tag.structure.input",
    "label"             => "meta.tag.structure.label",
    "legend"            => "meta.tag.structure.legend",
    "li"                => "meta.tag.structure.li",
    "main"              => "meta.tag.structure.main",
    "map"               => "meta.tag.structure.map",
    "meter"             => "meta.tag.structure.meter",
    "nav"               => "meta.tag.structure.nav",
    "noframes"          => "meta.tag.structure.noframes",
    "optgroup"          => "meta.tag.structure.optgroup",
    "option"            => "meta.tag.structure.option",
    "ol"                => "meta.tag.structure.ol",
    "output"            => "meta.tag.structure.output",
    "p"                 => "meta.tag.structure.p",
    "pre"               => "meta.tag.structure.pre",
    "progress"          => "meta.tag.structure.progress",
    "section"           => "meta.tag.structure.section",
    "select"            => "meta.tag.structure.select",
    "summary"           => "meta.tag.structure.summary",
    "svg"               => "meta.tag.structure.svg",
    "table"             => "meta.tag.structure.table",
    "tbody"             => "meta.tag.structure.tbody",
    "td"                => "meta.tag.structure.td",
    "template"          => "meta.tag.structure.template",
    "textarea"          => "meta.tag.structure.textarea",
    "tfoot"             => "meta.tag.structure.tfoot",
    "th"                => "meta.tag.structure.th",
    "thead"             => "meta.tag.structure.thead",
    "tr"                => "meta.tag.structure.tr",
    "ul"                => "meta.tag.structure.ul",



    "a"                 => "meta.tag.inline.a",
    "abbr"              => "meta.tag.inline.abbr",
    "acronym"           => "meta.tag.inline.acronym",
    "area"              => "meta.tag.inline.area",
    "b"                 => "meta.tag.inline.b",
    "bdi"               => "meta.tag.inline.bdi",
    "bdo"               => "meta.tag.inline.bdo",
    "big"               => "meta.tag.inline.big",
    "br"                => "meta.tag.inline.br",
    "cite"              => "meta.tag.inline.cite",
    "code"              => "meta.tag.inline.code",
    "data"              => "meta.tag.inline.data",
    "del"               => "meta.tag.inline.del",
    "dfn"               => "meta.tag.inline.dfn",
    "em"                => "meta.tag.inline.em",
    "font"              => "meta.tag.inline.font",
    "i"                 => "meta.tag.inline.i",
    "ins"               => "meta.tag.inline.ins",
    "kbd"               => "meta.tag.inline.kbd",
    "mark"              => "meta.tag.inline.mark",
    "q"                 => "meta.tag.inline.q",
    "rp"                => "meta.tag.inline.rp",
    "rt"                => "meta.tag.inline.rt",
    "ruby"              => "meta.tag.inline.ruby",
    "s"                 => "meta.tag.inline.s",
    "samp"              => "meta.tag.inline.samp",
    "small"             => "meta.tag.inline.small",
    "span"              => "meta.tag.inline.span",
    "strike"            => "meta.tag.inline.strike",
    "strong"            => "meta.tag.inline.strong",
    "sub"               => "meta.tag.inline.sub",
    "sup"               => "meta.tag.inline.sup",
    "time"              => "meta.tag.inline.time",
    "tt"                => "meta.tag.inline.tt",
    "u"                 => "meta.tag.inline.u",
    "var"               => "meta.tag.inline.var",
    "wbr"               => "meta.tag.inline.wbr",



    "base"              => "meta.tag.metadata.base",
    "basefont"          => "meta.tag.metadata.basefont",
    "link"              => "meta.tag.metadata.link",
    "meta"              => "meta.tag.metadata.meta",
    "noscript"          => "meta.tag.metadata.noscript",
    "script"            => "meta.tag.metadata.script",
    "style"             => "meta.tag.metadata.style",
    "title"             => "meta.tag.metadata.title",



    "applet"            => "meta.tag.object.applet",
    "audio"             => "meta.tag.object.audio",
    "canvas"            => "meta.tag.object.canvas",
    "embed"             => "meta.tag.object.embed",
    "iframe"            => "meta.tag.object.iframe",
    "frame"             => "meta.tag.object.frame",
    "img"               => "meta.tag.object.img",
    "object"            => "meta.tag.object.object",
    "param"             => "meta.tag.object.param",
    "picture"           => "meta.tag.object.picture",
    "source"            => "meta.tag.object.source",
    "track"             => "meta.tag.object.track",
    "video"             => "meta.tag.object.video",



    "dir"               => "meta.tag.other.dir",
];
