<?php
/**
* @package      Aeon Digital Theme
* @author       Author Rianna Cantarelli
*/
namespace Loja\Controllers;

use CodeCraft\REST\Controller as Controller;
use CodeCraft\BasicTools\BasicTools as BT;


const AEON_CONSTANT = "Aeon Digital";





/**
* Class Description
*/
abstract class ClassName extends InheritedClass implements iInterface {

    public int $setInteger = 5;

    /**
    * Method Description
    *
    * @param string    $one                Parameter $one
    * @param string    [$two = "two"]      Parameter $two
    *
    * @return bool
    */
    public function MethodName(string $one, $two = "two") : bool
    {
        require_once('phpscript.php');
        include("teste");
        define('__ROOT__', dirname(dirname(__FILE__)));

        $routes = array();
        $var_string = "value";
        $var_number = 10;
        $var_bool = true;
        $var_instance = new \Teste\AnotherClass();
        $dt = new \DateTime();

        $var_cast = (int)"32";
        $pos = strpos($var_string);

        // Assoc Array
        $routes["Key"] = [
            "keyName_1"       => "value_1",
            "keyName_2"       => "value_2",
        ];

        $this->ExecuteMethod($one, "another arg", 10);
        $innerHTML = "<body class=\"use-\"" . $var_str . "\"class\">${var_str}</body>";

        BT::RetrieveHTTPInformation($__DomainConfig["DefaultApplication"]);

        $strSQL = "SELECT * FROM Teste WHERE column=$teste";
        $strSQL = "UPDATE Teste SET column='333' WHERE id=3";
        $strSQL = "DELETE FROM Teste WHERE id=3";
        $strSQL = "SHOW TABLES;";

        try {
            clone $var_instance;
            switch ($var_string) {
                case "val1":
                    break;
                case "val2":
                    break;
            }
        }
        catch (\Exception $e) {
            foreach($routes as $k => $v) {

            }
        }
        finally {
            for ($i = 0; $i < count($routes); $i++) {

            }
        }

        if (1 == 1 and 2 != 3) {
            $var_number++;
        } elseif (33 === 44) {
            // bla
        } else {
            // nha!
        }



        while (1 === 2) {
            // nheco
        }

        do {
            // bla!
        } while (2 === 1);

        return $one;
    }



    public function anotherFunction() {
        return "1";
    }


}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="pt-br" xml:lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <script src="js-file.js"></script>
        <![CDATA[ html/xml cdata section ]]>

        <title>Style &amp; Color</title>


        <style>
            /*
            Comment Block
            */
            body {
                font-family: arial;
            }

            h1, h2, h3, h4, h5, h6, table {
                background-color: #CCC;
                border: 1px solid;
                color: #39F;
                text-align: center;
                width: 100%;
            }

            p { display:block; width: 90%; font:normal 13px/19px tahoma, arial, sans-serif; color: #888; }


            cite:before { content: "- "; }
            cite:after { content: " they say! "; }

            #calendar {
                display: block;
                width: 600px;
                height: 100px;
                position: absolute;
                top: 10px;
                left: calc(50% - 300px);
            }

            .msg-sucess { color: #9988BB; }
            p.msg-sucess { box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15); }
            #calendar p.msg-sucess:hover { background-image: linear-gradient(#FAFAFA, #F1F1F1); }
        </style>


        <script>
            /*
                Comment Block
            */
            'use strict';

            var nClass = function(par1, par2) {
                par2 = (par2 === undefined) ? null : par2;

                var vBool = true;
                var vInt = 1;
                var vFloat = 1.34;
                var vString1 = "str1";
                var vString2 = 'str2';
                var vArray = [0, 1, 2, 3, 4, 5, 6];
                var vDate = new Date();


                if(par1 == false) {
                    console.log('a');
                }
                else {
                    if(1 == 1 || (1 != 2 && 1 != 3)) {
                        console.log('b');
                    }
                }


                var nTag = document.createElement('a');
                nTag.setAttribute('href', 'http://sample.com');
                nTag.textContent = 'push';

                if(par1 == undefined) {
                    window.open('http://www.anotherpage.com');
                }

                this.evoque(par1, par2);
                par2.evoqueAgain(par1);


                // JSON Object
                var json = {
                    'name' : 'object name',
                    'prop' : 'property value',
                    aprop : 'another property value'
                };


                switch(json.aprop) {
                    case '0' :
                        alert('here - 0');
                        break;

                    case '1' :
                        alert('here - 1');
                        break;

                    default :
                        alert('default');
                        break;
                }


                var c = 0;
                for(var it in json) {
                    c++;
                }


                for(var i=0; i<vArray.length; i++) {
                    c++;
                }


                return true;
            };
        </script>


    </head>
    <body>

        <!--
            Comment block
        -->


        <nav id="menu">
            <ul>
                <li>
                    <a href="link-to-another-page.html">link 01</a>
                </li>
                <li>
                    <a href="link-to-another-page.html">link 02</a>
                </li>
                <li>
                    <a href="link-to-another-page.html">link 03</a>
                </li>
                <li>
                    <a href="link-to-another-page.html">link 04</a>
                </li>
            </ul>
        </nav>


        <section id="sect-id" class="sect-class" tabindex="1">
            <h1>Section Title</h1>

            <article>
                <img src="image.jpg" alt="image description" />
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    <strong>Pellentesque luctus</strong>, elit &amp; fermentum aliquam fermentum, urna
                    ipsum venenatis nibh, vitae elementum quam mi non ipsum. Proin euismod tincidunt
                    condimentum. Duis convallis sodales congue. <em>Quisque efficitur</em> bibendum
                    massa in maximus. Maecenas sodales gravida dignissim. Nunc non ultricies nibh,
                    at feugiat libero. Integer sed convallis leo. <br />

                    <span class="icon"></span><br />
                    <span class="icon"></span><br />
                    <span class="icon"></span><br />
                </p>

                <table>
                    <thead>
                        <tr>
                            <th>Col h 01</th>
                            <th>Col h 02</th>
                            <th>Col h 03</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Col h 01</th>
                            <th>Col h 02</th>
                            <th>Col h 03</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td>Row content 01</td>
                            <td>Row content 02</td>
                            <td>Row content 03</td>
                        </tr>
                    </tbody>
                </table>


            </article>


        </section>





        <?php echo ""; ?>
    </body>
</html>
